let products = [
    {   
        id: 'T0001',
        name: 'Телевизор 55" Samsung UE55AU7100UXUA Black 5*',
        cost: 19499,
        img: 'assets/product/samsung42.jpg',
        sklad: 10,
        type: 'Samsung',
        tag: 10,
        smart: true,
        display: 55,
        wifi: true,
    },
    {   
        id: 'T0002',
        name: 'Телевизор 48" LG OLED48C14LB Black',
        cost: 32000,
        img: 'assets/product/lg48.jpg',
        sklad: 4,
        type: 'LG',
        tag: 3,
        smart: true,
        display: 48,
        wifi: true,
    },
    {   
        id: 'T0003',
        name: 'Телевизор Kivi 32H740LW',
        cost: 6000,
        img: 'assets/product/kivi32.jpg',
        sklad: 3,
        type: 'Kivi',
        tag: 4,
        smart: true,
        display: 32,
        wifi: true,
    },
    {   
        id: 'T0004',
        name: 'Телевизор 43" Xiaomi Mi TV P1 43 Black',
        cost: 11999,
        img: 'assets/product/xiaomi32.jpg',
        sklad: 3,
        type: 'Xiaomi',
        tag: 5,
        smart: true,
        display: 43,
        wifi: true,
    },
    {   
        id: 'T0005',
        name: 'Телевизор 75" Samsung QE75Q70AAUXUA Black',
        cost: 74999,
        img: 'assets/product/samsung42.jpg',
        sklad: 0,
        type: 'Samsung',
        tag: 2,
        smart: true,
        display: 75,
        wifi: true,
    },
    {   
        id: 'T0006',
        name: 'Телевизор Xiaomi Mi TV 4A 32',
        cost: 12999,
        img: 'assets/product/xiaomi32.jpg',
        sklad: 3,
        type: 'Xiaomi',
        tag: 6,
        smart: true,
        display: 32,
        wifi: true,
    },
    {   
        id: 'T0007',
        name: 'Телевизор LG 48',
        cost: 13999,
        img: 'assets/product/lg48.jpg',
        sklad: 3,
        type: 'LG',
        tag: 7,
        smart: true,
        display: 48,
        wifi: true,
    },
    {   
        id: 'T0008',
        name: 'Телевизор LG 32',
        cost: 4999,
        img: 'assets/product/lg48.jpg',
        sklad: 3,
        type: 'LG',
        tag: 1,
        smart: true,
        display: 32,
        wifi: true,
    },
    {   
        id: 'T0009',
        name: 'Телевизор Samsung 32',
        cost: 9999,
        img: 'assets/product/samsung42.jpg',
        sklad: 2,
        type: 'Samsung',
        tag: 12,
        smart: true,
        display: 32,
        wifi: true,
    },
    {   
        id: 'T0010',
        name: 'Телевизор 48" LG OLED48C14LB',
        cost: 29999,
        img: 'assets/product/lg48.jpg',
        sklad: 0,
        type: 'LG',
        tag: 0,
        smart: true,
        display: 48,
        wifi: true,
    },
    {   
        id: 'T0011',
        name: 'Телевизор Kivi 32H740LW',
        cost: 5999,
        img: 'assets/product/kivi32.jpg',
        sklad: 5,
        type: 'Kivi',
        tag: 22,
        smart: true,
        display: 32,
        wifi: true,
    },
];
function addData() {
    localStorage.setItem('data', JSON.stringify(data));
}